-- 035: rates belong to the assembly type
--
-- Every sheet in the workbook carries its own labor rates and its own
-- supervision ladder, and they are not close:
--
--                     04-Slab    10-Paving
--   forming            $0.45       $0.30   /SF
--   place & finish     $0.65       $0.55   /SF
--   wreck & clean      $0.10       $0.15   /SF
--   grading / cables   $0.65        none
--   supervision       SF/16,000   SF/25,000  per week
--
-- Until now there was one company value per key, so a paving section would have
-- priced its labor at slab rates — no error, just wrong, which is the failure
-- this project keeps finding.
--
-- Resolution order for any rate:
--
--   assembly_rates (this section's kind)  →  system_settings  →  code default
--
-- The company setting stays the fallback, so a kind that has nothing to say
-- about a key behaves exactly as it does today. Per-ESTIMATE overrides are
-- unchanged: they ride the is_manual flag on the stored line, which already
-- survives a recalc.
--
-- A row here means "this assembly DIFFERS", not "this is the value". mono_slab
-- deliberately gets no rows: it falls through to system_settings, so it behaves
-- exactly as it does today AND a company rate change still reaches it. Seeding
-- it from the live settings was tried first and was wrong — it would have
-- shadowed every future company change behind a copy made at migration time.
--
-- Acceptance: LBJ still totals $671,712.74, and changing labor_forming_sf still
-- moves a mono-slab section.

BEGIN;

CREATE TABLE IF NOT EXISTS assembly_rates (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        text NOT NULL,
    key         text NOT NULL,
    value       numeric(14, 4) NOT NULL,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (kind, key)
);

CREATE INDEX IF NOT EXISTS assembly_rates_kind_idx ON assembly_rates (kind);

COMMENT ON TABLE assembly_rates IS
    'Per-assembly rate overrides. Falls back to system_settings, then to the '
    'code default. One row per (kind, key).';

-- ---------------------------------------------------------------------------
-- paving: read off 10-PAVING (see claude/paving-spec.md)
-- ---------------------------------------------------------------------------

INSERT INTO assembly_rates (kind, key, value, note) VALUES
    ('paving', 'labor_forming_sf',        0.30,  'Sheet 10-PAVING row 61'),
    ('paving', 'labor_place_finish_sf',   0.55,  'Sheet 10-PAVING row 62'),
    ('paving', 'labor_wreck_sf',          0.15,  'Sheet 10-PAVING row 63'),
    -- Paving has no GRADING / CABLES line at all. Zero is the honest value and
    -- it shows on screen as a $0 line rather than vanishing; the line set for
    -- paving proper comes with the paving assembly itself.
    ('paving', 'labor_grading_sf',        0.00,  'No such line on 10-PAVING'),
    ('paving', 'labor_super_sf_per_week', 25000, 'Sheet 10-PAVING C70 = SF/25000'),
    -- Sidewalks are the same crew and the same shape of work; seeded alongside
    -- paving so a sidewalk section is not silently priced as a building slab.
    ('sidewalk', 'labor_forming_sf',        0.30, 'Assumed as paving until 11-Sidewalks is read'),
    ('sidewalk', 'labor_place_finish_sf',   0.55, 'Assumed as paving until 11-Sidewalks is read'),
    ('sidewalk', 'labor_wreck_sf',          0.15, 'Assumed as paving until 11-Sidewalks is read'),
    ('sidewalk', 'labor_grading_sf',        0.00, 'Assumed as paving until 11-Sidewalks is read'),
    ('sidewalk', 'labor_super_sf_per_week', 25000, 'Assumed as paving until 11-Sidewalks is read')
ON CONFLICT (kind, key) DO NOTHING;

COMMIT;

-- Verify:
--   SELECT kind, key, value FROM assembly_rates ORDER BY kind, key;
-- and LBJ must still read 671712.74.
